version: 2
references:
  docker_image: &docker_image
    docker:
    - image: gableroux/unity3d:2018.3.7f1
  setup_unity_license_env_var: &setup_unity_license_env_var
    command: |
      openssl version
      openssl aes-256-cbc -md md5 -d -in $UNITY_LICENCE_CONTENT -out Unity_v2018.x.ulf -k $KEY
      export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
      rm Unity_v2018.x.ulf
jobs:
  test_editmode:
    <<: *docker_image
    steps:
    # TODO: Add git to unity image so this is not required anymore
    # this will prevent following error on 'checkout' step:
    # Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
    - run:
        command: apt-get update && apt-get install -y git && git --version
    - checkout
    - run:
        <<: *setup_unity_license_env_var
    - run:
        environment:
          TEST_PLATFORM: editmode
        command: "./ci/test.sh"
    - store_artifacts:
        path: "$(pwd)/$TEST_PLATFORM-results.xml"
        destination: "$TEST_PLATFORM-results.xml"
  test_playmode:
    <<: *docker_image
    steps:
    - run:
        command: apt-get update && apt-get install -y git && git --version
    - checkout
    - run:
        <<: *setup_unity_license_env_var
    - run:
        environment:
          TEST_PLATFORM: playmode
        command: "./ci/test.sh"
    - store_artifacts:
        path: "$(pwd)/$TEST_PLATFORM-results.xml"
        destination: "$TEST_PLATFORM-results.xml"
  build_StandaloneLinux64:
    <<: *docker_image
    steps:
    - run:
        command: apt-get update && apt-get install -y git && git --version
    - checkout
    - run:
        <<: *setup_unity_license_env_var
    - run:
        environment:
          BUILD_TARGET: StandaloneLinux64
        command: "./ci/build.sh"
    - store_artifacts:
        path: "./Builds/"
workflows:
  version: 2
  test_and_build:
    jobs:
    - test_editmode
    - test_playmode
    - build_StandaloneLinux64

